version: 1.3.1.{build}
skip_tags: true
max_jobs: 1
configuration: Release
platform: x86
clone_depth: 50
image: Visual Studio 2017
before_build:
- ps: git clone "https://github.com/HearthSim/HearthDb" "HearthDb"
build:
  project: Hearthstone Collection Tracker.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(appveyor_build_version)'
after_build:
  7z a Graveyard.$(appveyor_build_version).zip "%APPVEYOR_BUILD_FOLDER%\Graveyard\bin\x86\Release\Graveyard.dll"
artifacts:
  - path: Graveyard.$(appveyor_build_version).zip
    name: Graveyard
